"""add category_id to items

Revision ID: 3f3945a3db61
Revises: 3295368fa753
Create Date: 2026-01-08 21:15:43.693889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f3945a3db61'
down_revision: Union[str, Sequence[str], None] = '3295368fa753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_foreign_key(None, 'items', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_column('items', 'category_id')
    # ### end Alembic commands ###
