"""add user_id to items

Revision ID: 5db428d20ecf
Revises: 71b0a940793e
Create Date: 2026-01-13 10:07:24.546530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db428d20ecf'
down_revision: Union[str, Sequence[str], None] = '71b0a940793e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_column('items', 'user_id')
    # ### end Alembic commands ###
