"""rename tags_id to tag_id

Revision ID: d3ee62d691b4
Revises: 31ae64b93fb1
Create Date: 2026-01-16 16:33:10.964203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ee62d691b4'
down_revision: Union[str, Sequence[str], None] = '31ae64b93fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_tags', sa.Column('tag_id', sa.Integer(), nullable=False))
    op.drop_constraint('item_tags_tags_id_fkey', 'item_tags', type_='foreignkey')
    op.create_foreign_key(None, 'item_tags', 'tags', ['tag_id'], ['id'])
    op.drop_column('item_tags', 'tags_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_tags', sa.Column('tags_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item_tags', type_='foreignkey')
    op.create_foreign_key('item_tags_tags_id_fkey', 'item_tags', 'tags', ['tags_id'], ['id'])
    op.drop_column('item_tags', 'tag_id')
    # ### end Alembic commands ###
